---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 4
  paused: false
  replicas: 8
  minReadySeconds: 20
  selector:
    matchLabels:
      role: feedback
  template:
    metadata:
      name: feedback
      labels:
        app: python
        role: feedback
        version: v1
    spec:
      containers:
        - name: app
          image: kalaiarasan33/feedback:v1
          ports:
            - containerPort: 80
              protocol: TCP
