---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedbackapi
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 4
  paused: false
  replicas: 8
  minReadySeconds: 20
  selector:
    matchLabels:
      role: feedbackapi
  template:
    metadata:
      name: feedbackapi
      labels:
        app: python
        role: feedbackapi
        version: v1
    spec:
      containers:
        - name: app
          image: kalaiarasan33/feedbackapi:v1
          ports:
            - containerPort: 5000
              protocol: TCP
